CC=gcc
OPTIONS=-lm -fopenmp -O3 `sdl2-config --cflags --libs`

all: geradorMandelbrot verMandelbrot

geradorMandelbrot: geradorMandelbrot.c
	$(CC) geradorMandelbrot.c $(OPTIONS) -o $@

verMandelbrot: verMandelbrot.c
	$(CC) verMandelbrot.c $(OPTIONS) -o $@

clean:
	rm verMandelbrot geradorMandelbrot
